-- TaskUI Database Schema
-- SQLite Schema Definition for Reference
-- This file is auto-generated by SQLAlchemy, but maintained for documentation

-- Task Lists Table
-- Stores the different task list categories (Work, Home, Personal, etc.)
CREATE TABLE IF NOT EXISTS task_lists (
    id VARCHAR(36) PRIMARY KEY,  -- UUID as string
    name VARCHAR(100) NOT NULL,  -- List name (e.g., "Work", "Home")
    created_at DATETIME NOT NULL -- Creation timestamp
);

-- Tasks Table
-- Stores individual tasks with hierarchical nesting support
CREATE TABLE IF NOT EXISTS tasks (
    id VARCHAR(36) PRIMARY KEY,           -- UUID as string
    title VARCHAR(500) NOT NULL,          -- Task title/name
    notes TEXT,                            -- Optional task notes/description

    -- Status Flags
    is_completed BOOLEAN NOT NULL DEFAULT 0,  -- Completion status
    is_archived BOOLEAN NOT NULL DEFAULT 0,   -- Archive status

    -- Hierarchy
    parent_id VARCHAR(36),                -- Parent task ID (NULL for root tasks)
    level INTEGER NOT NULL DEFAULT 0,     -- Nesting level (0-2)
    position INTEGER NOT NULL DEFAULT 0,  -- Order within siblings

    -- Relationships
    list_id VARCHAR(36) NOT NULL,         -- Foreign key to task_lists

    -- Timestamps
    created_at DATETIME NOT NULL,         -- Creation timestamp
    completed_at DATETIME,                -- Completion timestamp (NULL if not completed)
    archived_at DATETIME,                 -- Archive timestamp (NULL if not archived)

    -- Foreign Key Constraints
    FOREIGN KEY (list_id) REFERENCES task_lists(id) ON DELETE CASCADE
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_tasks_list_id ON tasks(list_id);
CREATE INDEX IF NOT EXISTS idx_tasks_parent_id ON tasks(parent_id);
CREATE INDEX IF NOT EXISTS idx_tasks_level ON tasks(level);
CREATE INDEX IF NOT EXISTS idx_tasks_position ON tasks(position);
CREATE INDEX IF NOT EXISTS idx_tasks_completed ON tasks(is_completed);
CREATE INDEX IF NOT EXISTS idx_tasks_archived ON tasks(is_archived);

-- Sample Default Lists
-- These would typically be inserted on first run
-- INSERT INTO task_lists (id, name, created_at) VALUES
--     ('00000000-0000-0000-0000-000000000001', 'Work', datetime('now')),
--     ('00000000-0000-0000-0000-000000000002', 'Home', datetime('now')),
--     ('00000000-0000-0000-0000-000000000003', 'Personal', datetime('now'));
